### ISSUE TITLE
Paper 

### ISSUE THREAD

**Issue by wq-july** [Navy-RISE-Lab/ground-texture-slam#1]
Great job! Can you provide the  paper or a runnable dataset? I didn't find the paper you mentioned.

**Comment by Navy-RISE-Lab** [comment]
The paper is still under review. Once accepted, I'll add it. I'll leave this issue open as a reminder.

**Comment by Navy-RISE-Lab** [comment]
@July-creater version 1.0.2 references the preprint of the paper and how to get the dataset in the README. I'll go ahead and close this now.
