### ISSUE TITLE
How to perform VO?

### ISSUE THREAD

**Issue by yangzheng-yz** [Navy-RISE-Lab/ground-texture-slam#2]
Hello, Thanks for your great work!
Could you tell me how to perform pure VO using this project?

Plus, I run the code for full SLAM on my own dataset, but the processing time is extremely expensive (about 2-3s per frame). Is it normal?

**Comment by yangzheng-yz** [comment]
Now I know it is because you build the opencv with "-DBUILD_LIST=core,features2d,flann". So I would like to know if you prapare a method for I/O of dataset?

**Comment by yangzheng-yz** [comment]
comment the final line of function _void GroundTextureSLAM::insertMeasurement(const cv::Mat& image)_ can close the loop detection module.

The reason for slow processing speed is exactly from the loop closing module. The project will review all of previous frames (no key frames) to check loop, so expensive.

**Comment by gityeezy** [comment]
Hello, Thanks for your great work! I'd like to ask, how do you run the Ground Texture SLAM algorithm, how do you compile and run it, what changes do you need to make, there are only some examples in his homepage, I don't really understand how to use it? thank u.
