### ISSUE TITLE
What's definition of image frame x-axis, y-axis, z-axis?

### ISSUE THREAD

**Issue by narutojxl** [Navy-RISE-Lab/ground-texture-slam#4]
Hello author, 
Thanks for your very good code readability and sharing to community to learn. I have a question about image frame's x-axis, y-axis, z-axis definition in code `ImageParser::ImageParser(Options options) ctor` in ImageParser.cpp, namely variable `image_2_camera_transform` meaning. 

Best regards
narutojxl

**Comment by Navy-RISE-Lab** [comment]
Thanks! The output of the function `ImageParser::parseImage` has a vector of `gtsam::Point2`. Those points are measured from the robot's frame of reference. The `image_2_camera_transform` is used to aid in the conversion from pixels coordinate for a keypoint into the robot's frame.

More specifically, after projecting a keypoint from pixels to real-world coordinates, it is in the _image frame_ which follows the image standard of positive X axis to the right along the image edge (which is also to the right of the camera) and positive Y axis down the image edge (which is also below the camera) with the origin located in the middle of the image. That transform converts the points into a _camera frame_ that follows typical robotics convention of positive X axis out through the lens of the camera and positive Y axis to the left of the camera. Those points are then transformed into the robot's frame using the pose of the camera as measured from the robot's frame of reference.

Does that help? If not, let me know and I can elaborate more.

**Comment by narutojxl** [comment]
Thanks for author detailed reply. 
> "the image_frame with the origin located in the middle of the image."

as I understand, its origin is located with camera optical center,  also is the same with camera_frame. 

As i understand, if my camera_frame axis definition is the same with image_frame,  we do not need the transform `image_2_camera_transform = Rx(-pi/2) * Ry(pi/2)` in the code, right? 
![image](https://github.com/Navy-RISE-Lab/ground-texture-slam/assets/6205343/744a508a-aa64-43b2-b5d4-93c58a1eaef6)

**Comment by Navy-RISE-Lab** [comment]
> its origin is located with camera optical center, also is the same with camera_frame.

Correct. Which is also why no translation component is needed in the transform, just rotation.

> if my camera_frame axis definition is the same with image_frame, we do not need the transform

Also correct. I chose to have _camera_frame_ and _image_frame_ different to match conventions seen in other software packages, but what you described works too.

Also, great diagram! That makes the setup very clear.

**Comment by narutojxl** [comment]
Thanks author, my problem is solved, close it now!
